# This is a basic workflow to help you get started with Actions

name: swell-discover-nightly

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false

defaults:
  run:
    shell: bash

env:
  CI_ROOT: /discover/nobackup/gmao_ci/swell/nightly

jobs:
  swell-nightly:
  
    runs-on: nccs-discover
    
    steps:
    
      - name: validate-workflow
        run: |
          /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} swell
     #    /home/jardizzo/bin/nams_check.py "${{ github.event.label.name }}" swell
     
      - name: establish-workflow-status
        run: |
          if [ -f "$CI_ROOT/.lock" ]; then echo "Lock file present. Aborting."; exit 1; fi
          touch $CI_ROOT/.lock
          
      - name: exit-workflow
        run: |
          rm -f $CI_ROOT/.lock
          sleep 300
          echo "Workflow complete"
