# This is the test bed for GEOS on GPU

name: geosongpu-ondemand

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      experiment_name:
        required: true
        type: string
      experiment_action:
        required: true
        type: string
      geosongpu_ci_ref:
        required: true
        type: string

env:
  CI_ROOT: /discover/nobackup/gmao_ci/geosongpu

defaults:
  run:
    shell: bash

jobs:
  geosongpu-ondemand:
  
    runs-on: nccs-discover
    timeout-minutes: 600
    
    steps:
    
      - name: validate-workflow
        run: |
          /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} geosongpu

      # - name: establish-workflow-status
      #   run: |
      #     if [ -f "$CI_ROOT/.lock" ]; then echo "Lock file present. Aborting."; exit 1; fi
      #     mkdir -p $CI_ROOT
      #     touch $CI_ROOT/.lock

      - name: get-current-date
        run: echo "CI_DATETIME=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV

      - name: set-environment
        run: |
          echo "CI_DATETIME_EXP=$(date +'%Y%m%dT%H%M%S')_${{ inputs.experiment_name }}" >> $GITHUB_ENV
          echo "CI_WORKSPACE=$CI_ROOT/work/$CI_DATETIME_EXP" >> $GITHUB_ENV
          echo "CI_ARTIFACT=$CI_ROOT/artifact/$CI_DATETIME_EXP" >> $GITHUB_ENV

      - name: create-CI-workspace
        run: |
          mkdir -p $CI_ARTIFACT
          mkdir -p $CI_WORKSPACE
          cd $CI_ROOT
          /bin/rm -f active
          ln -s $CI_WORKSPACE active
          
      - name: acquire-geosongpu-ci
        uses: actions/checkout@v3
        with:
          repository: GEOS-ESM/geosongpu-ci
          ref: ${{ inputs.geosongpu_ci_ref }}
          path: geosongpu-ci

      - name: experiment-run
        run: |
          cd $CI_WORKSPACE
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install $GITHUB_WORKSPACE/geosongpu-ci
          geosongpu_dispatch ${{ inputs.experiment_name }} ${{ inputs.experiment_action }} $CI_ARTIFACT
  
      - name: cleanup
        run: |
          cd $CI_WORKSPACE
          /bin/rm -r *

      # - name: exit-workflow
      #   run: |
      #     /bin/rm -f $CI_ROOT/.lock
      #     echo "Workflow complete"
  