# This is the test bed for GEOS on GPU

name: geosongpu-ondemand

on: workflow_call

env:
  CI_ROOT: $NOBACKUP/geosongpu

defaults:
  run:
    shell: bash

jobs:
  geosongpu-ondemand:
  
    runs-on: nccs-discover
    timeout-minutes: 600
    
    steps:
    
      - name: validate-workflow
        run: |
          /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} geosonpu

      - name: heartbeat
        run: |
          /discover/nobackup/fgdeconi/work/ci/heartbeat.py
