# This is a basic workflow to help you get started with Actions

name: swell-workflow01

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false

defaults:
  run:
    shell: bash

jobs:
  Run-task-workflow:
    if: ${{ github.actor == 'jardizzo' }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run-task-workflow
        run: |
          source /etc/profile.d/modules.sh
          source config/modules
          ./task.py
