# This is a basic workflow to help you get started with Actions

name: swell-workflow01

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false

defaults:
  run:
    shell: bash

env:
  CI_WORKSPACE: /discover/nobackup/jardizzo/CI/swell/nightly

jobs:
  swell-nightly:
  
    runs-on: self-hosted
    
    steps:
    
      - name: validate-workflow
        run: |
          /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} swell
          /home/jardizzo/bin/nams_check.py "${{ github.event.label.name }}" swell
          
      - name: acquire-CI-workflow
        uses: actions/checkout@v3
        with:
          repository: GEOS-ESM/CI-workflows-test
          path: CI-workflow
 
      - name: acquire-swell
        uses: actions/checkout@v3
        with:
          repository: GEOS-ESM/swell
          path: swell

      - name: acquire-jedi-bundle
        uses: actions/checkout@v3
        with:
          repository: GEOS-ESM/jedi_bundle
          path: jedi_bundle
          
      - name: install-CI-workflow
        run: |
          source $CI_WORKSPACE/CI-workflow/swell/discover/nightly/modules.sh
          mkdir -p $CI_WORKSPACE
          cp -r -p $GITHUB_WORKSPACE/CI-workflow $CI_WORKSPACE
          
      - name: install-swell
        run: |
          source $CI_WORKSPACE/CI-workflow/swell/discover/nightly/modules.sh
          mkdir -p $CI_WORKSPACE
          pip install --prefix=$CI_WORKSPACE/swell $GITHUB_WORKSPACE/swell
          
      - name: install-jedi-bundle
        run: |
          source $CI_WORKSPACE/CI-workflow/swell/discover/nightly/modules.sh
          mkdir -p $CI_WORKSPACE
          pip install --prefix=$CI_WORKSPACE/jedi_bundle $GITHUB_WORKSPACE/jedi_bundle
          
      - name: build-jedi
        run: |
          source $CI_WORKSPACE/CI-workflow/swell/discover/nightly/modules.sh
          $CI_WORKSPACE/CI-workflow/swell/discover/nightly/discover_run_build_jedi.sh
