# This is a basic workflow to help you get started with Actions

name: swell-workflow01

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false

defaults:
  run:
    shell: bash

env:
  WORK_DIR: /discover/nobackup/jardizzo/runner

jobs:
  swell-nightly:
    runs-on: self-hosted
    steps:
      - name: acquire-swell
        uses: actions/checkout@v3
        
      - name: acquire-jedi-bundle
        uses: actions/checkout@v3
        with:
          repository: GEOS-ESM/jedi_bundle
          
      - name: install-jedi-bundle
        run: |
          source /etc/profile.d/modules.sh
          source /discover/nobackup/jardizzo/JediOpt/install_modules
          mv swell/swell/jedi_bundle $WORK_DIR
          pip install --prefix=$WORK_DIR/install/jedi_bundle $WORK_DIR/jedi_bundle

 #    - name: build
 #      run: |
 #        /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} swell
 #        /home/jardizzo/bin/nams_check.py "${{ github.event.label.name }}" swell
 #        source /etc/profile.d/modules.sh
 #       source /discover/nobackup/jardizzo/JediOpt/install_modules
 #        pip install --prefix=/discover/nobackup/jardizzo/swell/install .
